### ISSUE TITLE
Create engine for AuRa integration in Geth

### ISSUE THREAD

**Issue by 5chdn** [goerli/go-ethereum-aura#1]
- [ ] review Clique engine implementation in Geth
- [ ] review Rinkeby specification in Geth
- [ ] prepare AuRa engine in Geth

**Comment by ansermino** [comment]
Questions from Aura Spec (https://wiki.parity.io/Aura):
- [x] Confirm block time (15 seconds currently)
    **4** seconds https://github.com/goerli/testnet/blob/master/parity/goerli.json#L7
- [x] clarify how validators are added
- [x] What is `C[K..]`
- [x] How are empty block producers rewarded?
- [x] Are empty step messages enabled in Parity? Lower priority task (empty block instead)?
    no, that's disabled, low priority task
- [x] What are the parity maximumEmptyStepTransition?
    not to be implemented or low priority task (see above)
- [x] What is the empty step message format? (Parity)
    not to be implemented or low priority task (see above)
- [x] Does the hash in the empty step messages change for consecutive empty steps?
    not to be implemented or low priority task (see above)
- [x] What is a `blockchain address` (ie `--engine-signer VALIDATOR-ADDRESS`)?
    that's the public address of the authority node allowed to seal blocks
- [x] What is the role of `--force-sealing` with empty step messages?
