### ISSUE TITLE
Port AuRa engine from Rust to Go

### ISSUE THREAD

**Issue by 5chdn** [goerli/go-ethereum-aura#2]
- [ ] review AuRa consensus engine in Parity
- [ ] port consensus engine to Go

**Comment by noot** [comment]
this is a preliminary list of functions that may need to be modified. however, not all of these may need to be modified. there are likely many many more places that /do/ need to be modified.

Changes to be made in aura.go (implementing Engine interface):
Author():
- [x] Pull the author from block header (not coinbase) 

VerifyHeader():
- [x] Determine what checks need to be placed here
- [x] Implement checks
- [ ] (???) mixDigest; i don't think parity implements mixDigest

VerifyHeaders():
- [x] Confirm not changes needed

VerifyUncles():
- [x] Return true always

VerifySeal():
- [x] make sure the signature of the header is the correct elected authority based on turns

Prepare()
- [x] Determine if no changes necessary (ie. no additional fields in header)

Finalize()
- [x] Add block reward (5 eth)
- [ ] Add tx fees (assumption)

Seal()
- [x] Verify no changes needed
- [x] make sure to sign correct block

SealHash()
- [x] Verify no changes needed

CalcDifficulty()
- [x] Verify no changes needed (presumable a constant)

Other Functions maybe needed:

verifyCascadingFields():
- [x] If the block is a checkpoint block, verify the signer list

snapshot()
- [x] how often are snapshots created? -> snapshots are not necessary for Aura, as long as we store validators somewhere and they are static
